version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    environment:
      DATABASE_URL: postgresql://postgres:newpassword@db/graphnote_development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: development
      BUNDLE_DEPLOYMENT: 0
      BUNDLE_WITHOUT: ""
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    volumes:
      - .:/graph-note
      - bundle:/usr/local/bundle
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle: